name: SEO Audit
on:
    schedule:
        - cron: '*/10 * * * *'
    workflow_dispatch:

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: treosh/lighthouse-ci-action@v3
              with:
                  urls: |
                      https://scion-softworks.github.io
                      https://scion-softworks.github.io/#/about-us
                      https://scion-softworks.github.io/#/contacts
                      https://scion-softworks.github.io/#/projects
                      https://scion-softworks.github.io/#/contribute
                      https://scion-softworks.github.io/#/404
                  uploadArtifacts: false
